# yaml-language-server: $schema=../github-workflow.schema.json
name: Deploy action
# run-name: ${{ github.actor }} pushed to production 🚀
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-bookworm
      options: --dns 100.100.100.100
    steps:
      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install -y git ssh rsync
      - name: Check out repository code
        run: |
          echo "Cloning ${{ github.repository }} @ ${{ github.ref_name }}"
          echo "$SSH_KEY" > /tmp/deploy.key && \
          echo "" >> /tmp/deploy.key && \
          chmod 600 /tmp/deploy.key && \
          GIT_SSH_COMMAND="ssh -i /tmp/deploy.key -o StrictHostKeyChecking=no" \
          git clone git@gitea.ts.millim.no:millim/www . && \
          git checkout ${{ github.ref_name }} && \
          git submodule update --init --recursive
        env:
          SSH_KEY: ${{ secrets.REPO_DEPLOY_KEY }}
      - name: Create .env file
        run: |
          cat <<EOF
          DJANGO_DEBUG=$DJANGO_DEBUG
          SECRET_KEY=$SECRET_KEY
          ALLOWED_HOSTS=$ALLOWED_HOSTS
          EOF >> .env
        env:
          DJANGO_DEBUG: ${{ vars.DJANGO_DEBUG }}
          SECRET_KEY: ${{ vars.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
      - name: Fetch the stage target private key
        if: ${{ github.ref == 'refs/heads/stage' }}
        env:
          SSH_KEY: ${{ secrets.STAGE_PRIVKEY }}
        run: |
          echo "$SSH_KEY" > /tmp/target.key
          echo "" >> /tmp/target.key
          chmod 600 /tmp/target.key
      - name: Define stage host
        if: ${{ github.ref == 'refs/heads/stage' }}
        env:
          target: ${{ vars.STAGE_HOST }}
        run: |
          echo $TARGET > /tmp/target_path.txt
      - name: Fetch the deploy target private key
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          SSH_KEY: ${{ secrets.DEPLOY_PRIVKEY }}
        run: |
          echo "$SSH_KEY" > /tmp/target.key
          echo "" >> /tmp/target.key
          chmod 600 /tmp/target.key
      - name: Define target host
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          TARGET: ${{ vars.DEPLOY_HOST }}
        run: |
          echo $TARGET > /tmp/target_path.txt
      - name: Deploy
        run: |
          chmod -R 777 .
          rsync -a -e "ssh -o \"StrictHostKeyChecking off\" -i /tmp/target.key" --exclude-from=exclude.txt ./ $(cat /tmp/target_path.txt)
      - name: Install dependencies on server
        run: |
          docker exec web-2 bash "cd /srv/portfolio/www && bash scripts/setup.sh"
